# TaLoS configuration: sparsity=0.7, calibration_rounds=4

# Federated learning parameters
num-server-rounds = 30
num-classes-per-partition = 10
local-epochs = 8
fraction-train = 0.1

# Sparse fine-tuning with TaLoS
use-sparse-finetuning = true
sparsity-ratio = 0.7
num-calibration-rounds = 4

# Wandb configuration
group = "TEST-Fisher-task-arithmetic-s70-r4"
notes = "TEST if Fisher Matrix computation makes improvemets to current implementation"
